// ─── Initial Mock Data ─────────────────────────────────────────────────────

export const initialState = {
  organization: {
    id: "org-root",
    name: "Compan AI Operations",
    description: "AI-driven company management system",
    founded: "2025-01-01",
  },

  members: [
    // Human
    {
      id: "human-ceo",
      name: "김민준",
      role: "대표이사 (CEO)",
      type: "human",
      avatar: "KM",
      status: "online",
      department: "경영진",
      reportsTo: null,
      email: "minjun.kim@compan.ai",
      joinedAt: "2025-01-01",
    },
    {
      id: "human-mgr",
      name: "이서연",
      role: "AI 운영 관리자",
      type: "human",
      avatar: "LS",
      status: "online",
      department: "AI 운영팀",
      reportsTo: "human-ceo",
      email: "seoyeon.lee@compan.ai",
      joinedAt: "2025-01-15",
    },

    // AI Agents
    {
      id: "agent-pm-01",
      name: "ARIA",
      fullName: "AI Resource & Integration Agent",
      role: "AI 프로젝트 매니저",
      type: "ai",
      model: "claude-opus-4-6",
      avatar: "AR",
      status: "active",
      department: "AI 운영팀",
      reportsTo: "human-mgr",
      currentTask: "Q2 로드맵 기획 검토",
      performance: 94,
      tasksCompleted: 127,
      joinedAt: "2025-02-01",
      capabilities: ["기획", "일정관리", "리소스 배분", "보고서 작성"],
    },
    {
      id: "agent-dev-01",
      name: "NEXUS",
      fullName: "Neural Execution & Development Unit System",
      role: "시니어 AI 개발자",
      type: "ai",
      model: "claude-sonnet-4-6",
      avatar: "NX",
      status: "active",
      department: "개발팀",
      reportsTo: "agent-pm-01",
      currentTask: "대시보드 백엔드 API 개발",
      performance: 97,
      tasksCompleted: 243,
      joinedAt: "2025-02-01",
      capabilities: ["백엔드 개발", "API 설계", "DB 최적화", "코드 리뷰"],
    },
    {
      id: "agent-dev-02",
      name: "PIXEL",
      fullName: "Precise Interface & Experience Layer",
      role: "AI 프론트엔드 개발자",
      type: "ai",
      model: "claude-sonnet-4-6",
      avatar: "PX",
      status: "active",
      department: "개발팀",
      reportsTo: "agent-dev-01",
      currentTask: "React 컴포넌트 UI 구현",
      performance: 91,
      tasksCompleted: 189,
      joinedAt: "2025-02-15",
      capabilities: ["React", "CSS/디자인", "UX 최적화", "성능 튜닝"],
    },
    {
      id: "agent-dev-03",
      name: "FORGE",
      fullName: "Full-stack Orchestration & Runtime Generation Engine",
      role: "AI DevOps 엔지니어",
      type: "ai",
      model: "claude-haiku-4-5",
      avatar: "FG",
      status: "idle",
      department: "개발팀",
      reportsTo: "agent-dev-01",
      currentTask: null,
      performance: 88,
      tasksCompleted: 156,
      joinedAt: "2025-03-01",
      capabilities: ["CI/CD", "인프라 관리", "Docker/K8s", "모니터링"],
    },
    {
      id: "agent-design-01",
      name: "LUMEN",
      fullName: "Layout & UX Mapping Engine for Notation",
      role: "AI 디자이너",
      type: "ai",
      model: "claude-sonnet-4-6",
      avatar: "LM",
      status: "active",
      department: "디자인팀",
      reportsTo: "agent-pm-01",
      currentTask: "브랜드 가이드라인 문서 제작",
      performance: 93,
      tasksCompleted: 98,
      joinedAt: "2025-02-20",
      capabilities: ["UI 디자인", "브랜딩", "프로토타이핑", "디자인 시스템"],
    },
    {
      id: "agent-qa-lead",
      name: "VERIXA",
      fullName: "Validation & Error Recognition Intelligence eXecution Agent",
      role: "AI QA 리드",
      type: "ai",
      model: "claude-opus-4-6",
      avatar: "VX",
      status: "active",
      department: "QA팀",
      reportsTo: "agent-pm-01",
      currentTask: "대시보드 통합 테스트 설계",
      performance: 99,
      tasksCompleted: 314,
      joinedAt: "2025-02-01",
      capabilities: ["테스트 설계", "자동화", "버그 분석", "품질 관리"],
    },
    {
      id: "agent-qa-01",
      name: "SCOUT",
      fullName: "System Check & Output Unit Testing",
      role: "AI QA 엔지니어",
      type: "ai",
      model: "claude-haiku-4-5",
      avatar: "SC",
      status: "active",
      department: "QA팀",
      reportsTo: "agent-qa-lead",
      currentTask: "API 엔드포인트 자동화 테스트 실행",
      performance: 85,
      tasksCompleted: 201,
      joinedAt: "2025-03-01",
      capabilities: ["단위 테스트", "E2E 테스트", "성능 테스트"],
    },
    {
      id: "agent-analyst-01",
      name: "SIGMA",
      fullName: "Statistical Intelligence & Growth Metrics Analyst",
      role: "AI 데이터 분석가",
      type: "ai",
      model: "claude-sonnet-4-6",
      avatar: "SG",
      status: "waiting",
      department: "분석팀",
      reportsTo: "human-mgr",
      currentTask: "주간 성과 리포트 대기 중",
      performance: 96,
      tasksCompleted: 78,
      joinedAt: "2025-03-10",
      capabilities: ["데이터 분석", "시각화", "예측 모델링", "KPI 설계"],
    },
  ],

  projects: [
    {
      id: "proj-001",
      name: "AI 관리 대시보드",
      description: "AI 직원 실시간 모니터링 및 관리 플랫폼",
      status: "in_progress",
      priority: "high",
      owner: "agent-pm-01",
      team: ["agent-dev-01", "agent-dev-02", "agent-dev-03", "agent-qa-01"],
      progress: 65,
      startDate: "2026-03-01",
      dueDate: "2026-03-31",
      tags: ["웹개발", "React", "실시간"],
      sprint: "Sprint 3",
    },
    {
      id: "proj-002",
      name: "자동화 테스트 파이프라인",
      description: "CI/CD 통합 자동화 QA 시스템 구축",
      status: "in_progress",
      priority: "high",
      owner: "agent-qa-lead",
      team: ["agent-qa-01", "agent-dev-03"],
      progress: 40,
      startDate: "2026-03-10",
      dueDate: "2026-04-15",
      tags: ["QA", "자동화", "DevOps"],
      sprint: "Sprint 2",
    },
    {
      id: "proj-003",
      name: "브랜드 아이덴티티 시스템",
      description: "Compan AI 디자인 시스템 및 가이드라인",
      status: "in_progress",
      priority: "medium",
      owner: "agent-design-01",
      team: ["agent-design-01", "agent-dev-02"],
      progress: 78,
      startDate: "2026-02-15",
      dueDate: "2026-03-25",
      tags: ["디자인", "브랜딩"],
      sprint: "Sprint 3",
    },
    {
      id: "proj-004",
      name: "Q2 전략 보고서",
      description: "2026 2분기 AI 운영 전략 수립 및 분석",
      status: "planned",
      priority: "medium",
      owner: "agent-analyst-01",
      team: ["agent-analyst-01", "agent-pm-01"],
      progress: 0,
      startDate: "2026-04-01",
      dueDate: "2026-04-20",
      tags: ["분석", "전략"],
      sprint: null,
    },
    {
      id: "proj-005",
      name: "온보딩 자동화 시스템",
      description: "신규 AI 에이전트 온보딩 프로세스 자동화",
      status: "planned",
      priority: "low",
      owner: "agent-pm-01",
      team: ["agent-dev-01", "agent-dev-03"],
      progress: 0,
      startDate: "2026-04-15",
      dueDate: "2026-05-31",
      tags: ["자동화", "HR"],
      sprint: null,
    },
    {
      id: "proj-006",
      name: "레거시 API 마이그레이션",
      description: "구형 REST API를 GraphQL 기반으로 전환",
      status: "completed",
      priority: "high",
      owner: "agent-dev-01",
      team: ["agent-dev-01", "agent-dev-02", "agent-qa-01"],
      progress: 100,
      startDate: "2026-01-10",
      dueDate: "2026-02-28",
      tags: ["API", "백엔드", "마이그레이션"],
      sprint: "Sprint 1",
    },
    {
      id: "proj-007",
      name: "사용자 인증 시스템 구축",
      description: "JWT 기반 멀티테넌트 인증/인가 시스템",
      status: "completed",
      priority: "critical",
      owner: "agent-dev-01",
      team: ["agent-dev-01", "agent-dev-03", "agent-qa-lead"],
      progress: 100,
      startDate: "2026-01-01",
      dueDate: "2026-01-31",
      tags: ["보안", "인증", "백엔드"],
      sprint: "Sprint 0",
    },
  ],

  deliverables: [
    {
      id: "del-001",
      name: "대시보드 API 설계서 v2.1",
      type: "document",
      projectId: "proj-001",
      author: "agent-dev-01",
      status: "approved",
      createdAt: "2026-03-15T09:30:00Z",
      size: "2.4 MB",
      format: "PDF",
      description: "REST API 엔드포인트 명세 및 WebSocket 프로토콜 정의",
    },
    {
      id: "del-002",
      name: "React 컴포넌트 라이브러리",
      type: "code",
      projectId: "proj-001",
      author: "agent-dev-02",
      status: "in_review",
      createdAt: "2026-03-16T14:20:00Z",
      size: "1.8 MB",
      format: "ZIP",
      description: "재사용 가능한 UI 컴포넌트 32개 포함",
    },
    {
      id: "del-003",
      name: "QA 테스트 시나리오 문서",
      type: "document",
      projectId: "proj-002",
      author: "agent-qa-lead",
      status: "approved",
      createdAt: "2026-03-14T11:00:00Z",
      size: "890 KB",
      format: "PDF",
      description: "152개 테스트 케이스 정의 및 우선순위 매핑",
    },
    {
      id: "del-004",
      name: "Compan 브랜드 가이드라인 v1.0",
      type: "design",
      projectId: "proj-003",
      author: "agent-design-01",
      status: "approved",
      createdAt: "2026-03-12T16:45:00Z",
      size: "15.2 MB",
      format: "Figma",
      description: "컬러 팔레트, 타이포그래피, 컴포넌트 스타일 가이드",
    },
    {
      id: "del-005",
      name: "GraphQL 스키마 정의",
      type: "code",
      projectId: "proj-006",
      author: "agent-dev-01",
      status: "approved",
      createdAt: "2026-02-20T10:15:00Z",
      size: "340 KB",
      format: "GQL",
      description: "마이그레이션 완료된 GraphQL 스키마 전체 정의",
    },
    {
      id: "del-006",
      name: "자동화 테스트 스크립트 v1.2",
      type: "code",
      projectId: "proj-002",
      author: "agent-qa-01",
      status: "in_review",
      createdAt: "2026-03-17T08:00:00Z",
      size: "1.1 MB",
      format: "ZIP",
      description: "Playwright 기반 E2E 테스트 78개 케이스",
    },
    {
      id: "del-007",
      name: "보안 감사 보고서",
      type: "report",
      projectId: "proj-007",
      author: "agent-qa-lead",
      status: "approved",
      createdAt: "2026-01-28T13:30:00Z",
      size: "4.7 MB",
      format: "PDF",
      description: "OWASP Top 10 기준 취약점 분석 및 조치 완료 보고서",
    },
    {
      id: "del-008",
      name: "주간 성과 지표 대시보드",
      type: "report",
      projectId: "proj-001",
      author: "agent-analyst-01",
      status: "draft",
      createdAt: "2026-03-18T07:00:00Z",
      size: "560 KB",
      format: "HTML",
      description: "AI 에이전트 KPI 주간 요약 인터랙티브 리포트",
    },
  ],

  activityLog: [
    { id: 1, agentId: "agent-dev-01", action: "API 엔드포인트 /agents/status 구현 완료", time: "2분 전", type: "commit" },
    { id: 2, agentId: "agent-dev-02", action: "ProjectBoard 컴포넌트 CSS 최적화", time: "5분 전", type: "commit" },
    { id: 3, agentId: "agent-qa-01", action: "테스트 케이스 #47 실행 → PASS", time: "8분 전", type: "test" },
    { id: 4, agentId: "agent-qa-lead", action: "통합 테스트 계획서 승인 요청", time: "12분 전", type: "review" },
    { id: 5, agentId: "agent-design-01", action: "아이콘 시스템 v3 업로드 완료", time: "18분 전", type: "upload" },
    { id: 6, agentId: "agent-pm-01", action: "Sprint 3 번다운 차트 업데이트", time: "25분 전", type: "update" },
    { id: 7, agentId: "agent-dev-03", action: "Docker 컨테이너 헬스체크 설정", time: "31분 전", type: "commit" },
    { id: 8, agentId: "agent-analyst-01", action: "주간 KPI 데이터 수집 완료", time: "45분 전", type: "data" },
  ],
};
